### ISSUE TITLE
Can skel be used in spineplayer3.8 version

### ISSUE THREAD

**Issue by lixue128** [alpacachen/spinePlayer#5]
body2 = new Spineplayer38({
                parent: this.$refs.threeEight,
                pngUrl: spine38.png,
                atlasUrl: spine38.atlas,
                skelUrl: spine38.skel,
                reduceFramerate: true,
            });

skelUrl？？Am I right？？Looking forward to the author's reply。Thanks

![image](https://user-images.githubusercontent.com/37533339/110325592-7d223700-8052-11eb-9568-07801d7ccf0e.png)

**Comment by alpacachen** [comment]
👌，i will reply you this morning



发自我的iPhone


------------------ Original ------------------

**Comment by alpacachen** [comment]
> body2 = new Spineplayer38({
> parent: this.$refs.threeEight,
> pngUrl: spine38.png,
> atlasUrl: spine38.atlas,
> skelUrl: spine38.skel,
> reduceFramerate: true,
> });
> 
> skelUrl？？Am I right？？Looking forward to the author's reply。Thanks
> 
> ![image](https://user-images.githubusercontent.com/37533339/110325592-7d223700-8052-11eb-9568-07801d7ccf0e.png)

不是skelUrl，是jsonUrl，你导出的spine源文件不是由png atlas json组成的嘛

**Comment by lixue128** [comment]
请问不支持二进制文件吗？

**Comment by alpacachen** [comment]
二进制文件应该无法用在web端，官方例子都是这样的，你可以让设计更改一下导出文件的方式

**Comment by lixue128** [comment]
奥 好的，谢谢啦🙏
